# Generated by Django 3.1.6 on 2021-02-15 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210215_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category'},
        ),
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
    ]
