# Generated by Django 3.1.6 on 2021-02-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210215_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(to='store.Product', verbose_name='Товар'),
        ),
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
    ]
