# Generated by Django 3.1.6 on 2021-02-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_cart_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(null=True, to='store.CartProduct', verbose_name='Товары'),
        ),
    ]
