# Generated by Django 3.1.6 on 2021-02-20 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0019_auto_20210219_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRefreshToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refresh', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
