# Generated by Django 3.1.6 on 2021-02-20 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0020_userrefreshtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrefreshtoken',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refresh', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userrefreshtoken',
            name='refresh',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
