# Generated by Django 3.1.6 on 2021-02-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20210221_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='images', verbose_name='Изображение'),
        ),
    ]
