# Generated by Django 3.1.6 on 2021-02-27 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_auto_20210227_2040'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Product',
        ),
    ]
