# Generated by Django 3.1.6 on 2021-03-13 07:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0030_userproductrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='viewers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
