# Generated by Django 3.1.6 on 2021-03-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_auto_20210323_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='a',
            field=models.CharField(default='fsd', max_length=41),
        ),
    ]
