# Generated by Django 3.1.6 on 2021-03-13 10:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0031_product_viewers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='viewers',
        ),
        migrations.AddField(
            model_name='product',
            name='reviewers',
            field=models.ManyToManyField(through='store.UserProductRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
