# Generated by Django 3.1.6 on 2021-03-23 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_cartproduct_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='a',
        ),
    ]
