# Generated by Django 3.1.6 on 2021-03-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_auto_20210313_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproductrelation',
            name='is_rated',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
