# Generated by Django 3.1.6 on 2021-03-23 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_remove_cartproduct_a'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
