# Generated by Django 3.1.6 on 2021-03-17 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0033_userproductrelation_is_rated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproductrelation',
            name='id',
        ),
        migrations.AlterField(
            model_name='userproductrelation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
