# Generated by Django 3.1.6 on 2021-03-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_cart_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='product_count',
            field=models.IntegerField(default=0),
        ),
    ]
