# Generated by Django 3.1.6 on 2021-03-24 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_cartproduct_product_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproduct',
            old_name='product_count',
            new_name='copy_count',
        ),
    ]
