# Generated by Django 3.1.6 on 2021-03-25 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_cart',
            field=models.BooleanField(default=False),
        ),
    ]
