# Generated by Django 3.1.6 on 2021-03-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_product_in_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='copy_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
