# Generated by Django 3.1.6 on 2021-03-27 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_cartproduct_copy_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='copy_price',
        ),
    ]
