# Generated by Django 3.1.6 on 2021-03-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_auto_20210327_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='comment',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
