# Generated by Django 3.1.6 on 2021-03-27 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_auto_20210327_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.feedback'),
        ),
    ]
