# Generated by Django 3.1.6 on 2021-03-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_auto_20210327_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='store.Feedback'),
        ),
    ]
