# Generated by Django 3.1.6 on 2021-03-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_userproductrelation_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproductrelation',
            name='info',
        ),
        migrations.AddField(
            model_name='userproductrelation',
            name='info',
            field=models.ManyToManyField(null=True, to='store.CartProduct'),
        ),
    ]
