# Generated by Django 3.1.6 on 2021-03-27 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_auto_20210328_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproductrelation',
            name='info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.cartproduct'),
        ),
    ]
