# Generated by Django 3.1.6 on 2021-03-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_auto_20210328_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproductrelation',
            name='is_rated',
            field=models.BooleanField(default=False),
        ),
    ]
