# Generated by Django 3.1.6 on 2021-03-28 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_auto_20210328_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproductrelation',
            name='info',
        ),
    ]
