# Generated by Django 3.1.6 on 2021-03-28 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0054_remove_userproductrelation_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproductrelation',
            name='info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.cartproduct'),
        ),
    ]
