# Generated by Django 3.1.6 on 2021-03-28 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0056_auto_20210328_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
    ]
