# Generated by Django 3.1.6 on 2021-03-28 14:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0057_remove_cart_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='UserProduct', to=settings.AUTH_USER_MODEL),
        ),
    ]
