# Generated by Django 3.1.6 on 2021-03-28 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0058_auto_20210328_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='in_cart',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
