# Generated by Django 3.1.6 on 2021-03-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0059_auto_20210328_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('true', models.BooleanField(default=True)),
                ('false', models.BooleanField(default=False)),
            ],
        ),
    ]
