# Generated by Django 3.1.6 on 2021-03-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0060_bool'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bool',
        ),
        migrations.AddField(
            model_name='product',
            name='false',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='true',
            field=models.BooleanField(default=True),
        ),
    ]
