# Generated by Django 3.1.6 on 2021-03-28 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0061_auto_20210329_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='false',
        ),
        migrations.RemoveField(
            model_name='product',
            name='true',
        ),
        migrations.RemoveField(
            model_name='userproductrelation',
            name='in_cart',
        ),
    ]
