# Generated by Django 3.1.6 on 2021-03-30 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0062_auto_20210329_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 30, 13, 42, 57, 179842)),
        ),
    ]
