# Generated by Django 3.1.6 on 2021-03-30 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0067_auto_20210330_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 30, 18, 11, 57, 340043)),
        ),
    ]
