# Generated by Django 3.1.6 on 2021-03-30 13:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0068_auto_20210330_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 30, 19, 53, 38, 104677)),
        ),
        migrations.AlterField(
            model_name='userproductrelation',
            name='info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.cartproduct'),
        ),
        migrations.AlterField(
            model_name='userproductrelation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.product'),
        ),
    ]
