# Generated by Django 3.1.6 on 2021-03-30 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0071_auto_20210330_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproductrelation',
            name='info',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 30, 20, 14, 3, 695299)),
        ),
    ]
