# Generated by Django 3.1.6 on 2021-03-31 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0073_auto_20210331_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 31, 13, 57, 32, 807092)),
        ),
    ]
