# Generated by Django 3.1.6 on 2021-04-04 15:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
import store.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0075_auto_20210331_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[store.validators.validate_percent_field]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 4, 21, 15, 5, 424390)),
        ),
        migrations.AlterField(
            model_name='feedbackrelation',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.feedback'),
        ),
    ]
