# Generated by Django 3.1.6 on 2021-04-03 16:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
import store.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0075_auto_20210331_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.IntegerField(default=0, validators=[store.validators.validate_percent_field]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 3, 22, 58, 37, 170618)),
        ),
        migrations.AlterField(
            model_name='feedbackrelation',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.feedback'),
        ),
    ]
