# Generated by Django 3.1.6 on 2021-04-03 17:17

import datetime
from django.db import migrations, models
import store.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0076_auto_20210403_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 3, 23, 17, 40, 838025)),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[store.validators.validate_percent_field]),
        ),
    ]
