# Generated by Django 3.1.6 on 2021-04-04 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0077_auto_20210403_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 4, 20, 26, 15, 321779)),
        ),
    ]
