# Generated by Django 3.1.6 on 2021-04-04 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0078_auto_20210404_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sale',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 4, 20, 54, 10, 142207)),
        ),
    ]
