# Generated by Django 3.1.6 on 2021-04-05 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0078_auto_20210405_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 5, 14, 32, 3, 448430)),
        ),
        migrations.AlterField(
            model_name='product',
            name='discountPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
