# Generated by Django 3.1.6 on 2021-04-05 10:39

import datetime
from django.db import migrations, models
import store.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0079_auto_20210405_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 5, 16, 39, 45, 499860)),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[store.validators.validate_percent_field]),
        ),
    ]
