# Generated by Django 3.1.6 on 2021-04-07 05:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0080_auto_20210405_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 7, 11, 31, 12, 391218)),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
