# Generated by Django 3.1.6 on 2021-04-11 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0085_auto_20210411_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='totalCount',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 11, 14, 17, 55, 491622)),
        ),
    ]
