# Generated by Django 3.1.6 on 2021-04-11 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0086_auto_20210411_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='totalCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 11, 14, 18, 1, 541077)),
        ),
    ]
