# Generated by Django 3.1.6 on 2021-04-11 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0087_auto_20210411_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='copyDiscountPrice',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='copyPrice',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 11, 14, 28, 49, 158765)),
        ),
    ]
