# Generated by Django 3.1.6 on 2021-04-12 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0088_auto_20210411_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='totalCount',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 12, 13, 59, 22, 952977)),
        ),
    ]
