# Generated by Django 3.1.6 on 2021-04-13 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0090_auto_20210413_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 13, 15, 54, 40, 712432)),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 13, 15, 54, 40, 716443)),
        ),
    ]
