# Generated by Django 3.1.6 on 2021-04-13 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0091_auto_20210413_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copyproduct',
            name='copyPrice',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 13, 17, 16, 18, 350434)),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 13, 17, 16, 18, 355446)),
        ),
    ]
