# Generated by Django 3.1.6 on 2021-04-14 12:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0093_auto_20210414_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 14, 18, 12, 27, 975350)),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 14, 18, 12, 27, 979361)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='orderData',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.orderdata'),
        ),
    ]
