# Generated by Django 3.1.6 on 2021-04-18 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0094_auto_20210414_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 18, 21, 52, 1, 310510)),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 18, 21, 52, 1, 314510)),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('Order processing', 'Order processing'), ('Order processing', 'Order is formed'), ('Order processing', 'Order for delivery'), ('Order processing', 'Order was sent to the post office')], max_length=50, null=True),
        ),
    ]
