# Generated by Django 3.1.6 on 2021-04-18 16:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0095_auto_20210418_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='products',
        ),
        migrations.AddField(
            model_name='copyproduct',
            name='orderProduct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.orderproduct'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 18, 22, 30, 39, 691288)),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 18, 22, 30, 39, 696299)),
        ),
    ]
