# Generated by Django 3.1.6 on 2021-04-18 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0096_auto_20210418_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='orderProducts',
            field=models.ManyToManyField(to='store.CopyProduct'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 18, 23, 18, 51, 333407)),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 18, 23, 18, 51, 337419)),
        ),
    ]
