# Generated by Django 3.1.6 on 2021-04-18 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0097_auto_20210418_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='orderProducts',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 18, 23, 22, 2, 445371)),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 18, 23, 22, 2, 450373)),
        ),
    ]
