# Generated by Django 3.1.6 on 2021-04-18 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0099_auto_20210418_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='orderProducts',
            new_name='products',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 18, 23, 56, 47, 770036)),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 18, 23, 56, 47, 774047)),
        ),
    ]
