# Generated by Django 3.1.6 on 2021-04-18 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0100_auto_20210418_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 19, 0, 50, 0, 134098)),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 19, 0, 50, 0, 138098)),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='CopyProduct',
        ),
    ]
