# Generated by Django 3.1.6 on 2021-04-18 18:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0101_auto_20210419_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='products',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 19, 0, 59, 45, 103474)),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 19, 0, 59, 45, 110486)),
        ),
        migrations.CreateModel(
            name='CopyProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyCount', models.IntegerField(null=True)),
                ('copyPrice', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('orderProduct', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OrderProducts', to='store.orderproduct')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
