# Generated by Django 3.1.6 on 2021-04-18 19:38

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0103_auto_20210419_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='products',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 19, 1, 38, 49, 830886)),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 19, 1, 38, 49, 834886)),
        ),
    ]
