# Generated by Django 3.1.6 on 2021-04-18 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0105_auto_20210419_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 19, 1, 46, 9, 978405)),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 19, 1, 46, 9, 982416)),
        ),
        migrations.DeleteModel(
            name='CopyProduct',
        ),
    ]
